### ISSUE TITLE
pyinstaller not found when freeze

### ISSUE THREAD

**Issue by jaydenC88** [mherrmann/fbs-tutorial#13]
I have pip install all the requirements and even pip install pyinstaller alone one more time just to make sure it is installed.
 I did `python3.5 -m pip install pyinstaller`, it gives:

`Requirement already satisfied: pyinstaller in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (3.3.1)
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyinstaller) (20.10.1)
Requirement already satisfied: pefile>=2017.8.1 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyinstaller) (2017.11.5)
Requirement already satisfied: macholib>=1.8 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pyinstaller) (1.9)
Requirement already satisfied: future in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pefile>=2017.8.1->pyinstaller) (0.16.0)
Requirement already satisfied: altgraph>=0.15 in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from macholib>=1.8->pyinstaller) (0.15)
`

but when I do `python3.5 -m fbs freeze`
it raised the following error:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fbs/__main__.py", line 4, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fbs/cmdline.py", line 17, in main
    args.cmd()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fbs/builtin_commands.py", line 38, in freeze
    freeze_mac()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fbs/freeze/mac.py", line 24, in freeze_mac
    run_pyinstaller(extra_args=pyinstaller_args + extra_pyinstaller_args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/fbs/freeze/__init__.py", line 21, in run_pyinstaller
    run(cmdline, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pyinstaller'`

**Comment by mherrmann** [comment]
Do you get an error when you just type `pyinstaller` into a Terminal?

The error you posted seems to me like you are not using a virtual environment. Is that correct? If yes, please try again with the virtual environment:

    git clone https://github.com/mherrmann/fbs-tutorial.git
    cd fbs-tutorial
    python3.5 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python -m fbs freeze

Hope this helps.

**Comment by mherrmann** [comment]
(You may have to replace `pip` and `python` in the above by `pip3` or `python3` or `python3.5`.)

**Comment by jaydenC88** [comment]
Thanks for your response but it prompted another issue which I am not sure how to deal with

![image](https://user-images.githubusercontent.com/23343740/42712565-22ae8786-86ba-11e8-97ae-b24bbd97374d.png)

**Comment by mherrmann** [comment]
This is unrelated to fbs. Please consult Google/Stackoverflow to find a solution. Sorry, but I don't have time to be of more help.

**Comment by fredrikaverpil** [comment]
@JiaEnChua the pip install error may be because you are on an old pip version. Make sure you are on the latest one.

I had lots of similar cert/ssl errors with Travis CI and a "python get-pip.py" fixed it all. 

http://pip.pypa.io/en/stable/installing/
