### ISSUE TITLE
Can't get fbs installer to work

### ISSUE THREAD

**Issue by AlexVillarra** [mherrmann/fbs-tutorial#39]
Whilst following the tutorial I encounter the following error on the last step (fbs installer):

```
(venv) MacBook-Pro-AVL:test Alex$ fbs installer
hdiutil: resize: failed. Invalid argument (22)
Traceback (most recent call last):
  File "/Users/Alex/Desktop/GUI_course/test/venv/bin/fbs", line 11, in <module>
    load_entry_point('fbs==0.8.6', 'console_scripts', 'fbs')()
  File "/Users/Alex/Desktop/GUI_course/test/venv/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/Alex/Desktop/GUI_course/test/venv/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/Alex/Desktop/GUI_course/test/venv/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 183, in installer
    create_installer_mac()
  File "/Users/Alex/Desktop/GUI_course/test/venv/lib/python3.6/site-packages/fbs/installer/mac/__init__.py", line 27, in create_installer_mac
    check_call(pdata, stdout=DEVNULL)
  File "/Users/Alex/.pyenv/versions/3.6.7/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/Alex/Desktop/GUI_course/test/venv/lib/python3.6/site-packages/fbs/installer/mac/create-dmg/create-dmg', '--no-internet-enable', '--volname', 'Tutorial', '--app-drop-link', '170', '10', '--icon', 'Tutorial.app', '0', '10', '/Users/Alex/Desktop/GUI_course/test/target/Tutorial.dmg', '/Users/Alex/Desktop/GUI_course/test/target/Tutorial.app']' returned non-zero exit status 22.**
```

I'm using Python 3.6.7
macOSX 10.15.3
fbs==0.8.6
PyInstaller==3.4
PyQt5==5.9.2

I tried using other versions of PyQt5 (tried PyQt5==5.14.2) and Python (3.7.1) and I get the same error.

**Comment by mherrmann** [comment]
Does this help? https://github.com/mherrmann/fbs/issues/105#issuecomment-487431034

**Comment by AlexVillarra** [comment]
Not really, I tried looking for a similar command in my .bash_profile and .bashrc file and have none. The result of echo $PATH throws:

> /Users/Alex/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin

**Comment by mherrmann** [comment]
I see. Then I don't know, sorry.

**Comment by Nechoj** [comment]
Just solved a similar problem on a MacBook Air.

After installation of the fbs package within a venv, the fbs installer did throw errors (permission problems, non-zero exit codes). Two steps were required:

1. chmod +x <path-to-venv>/lib/python3.xy/site-packages/fbs/installer/mac/create-dmg/create-dmg
2. nano <path-to-venv>/lib/python3.xy/site-packages/fbs/installer/mac/create-dmg/create-dmg

In the second step when editing the script, I made a small change to a comment and then saved the changes. This caused all \r line endings to be removed and replaces with \n only.
