### ISSUE TITLE
fbs freeze error: FileNotFoundError: Could not find msvcr110.dll on your PATH.

### ISSUE THREAD

**Issue by louistwiice** [mherrmann/fbs-tutorial#40]
Hi, 
I've being using fbs with python 3.6 to create an executable. After running the command `fbs freeze` this error came out to me. Even if I have installed Visual C++ Redistributable for Visual Studio 2012, the same result persists.
If someone could help me it would be really nice. Thanks you

Traceback (most recent call last):
  File "C:\Users\SZ\PycharmProjects\fbs project\venv\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.8.6', 'console_scripts', 'fbs')()
  File "C:\Users\SZ\PycharmProjects\fbs project\venv\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "C:\Users\SZ\PycharmProjects\fbs project\venv\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "C:\Users\SZ\PycharmProjects\fbs project\venv\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "C:\Users\SZ\PycharmProjects\fbs project\venv\lib\site-packages\fbs\freeze\windows.py", line 22, in freeze_windows
    _add_missing_dlls()
  File "C:\Users\SZ\PycharmProjects\fbs project\venv\lib\site-packages\fbs\freeze\windows.py", line 53, in _add_missing_dlls
    ) from None
FileNotFoundError: Could not find msvcr110.dll on your PATH. Please install the Visual C++ Redistributable for Visual Studio 2012 from:
    https://www.microsoft.com/en-us/download/details.aspx?id=30679

https://github.com/mherrmann/fbs/issues

**Comment by ChrisDongWooKim** [comment]
I have the same issue. Have you solved this problem? and HOW?

**Comment by AlfredThor** [comment]
I have the same issue.Have you solved this problem?and HOW?

**Comment by louistwiice** [comment]
Hi every one!!

Sadly I didn't solve the issue. I tried, I've read the documentation but the fbs freeze didn't work at all.
I think you should try the Pyinstaller. It worked really well for me.
Let me now if you have any questions

**Comment by ojomio** [comment]
I have this problem, too

**Comment by matetothde** [comment]
Hello everyone, 
I also had this issue and I managed to solve it.

In my case, on Windows 10, I had to install the Win10 SDK and then add the subfolder of the SDK installation which contains the .dll files to PATH in my environment variables.
After doing this, it works like a charme.

Regards

**Comment by 3DMiller** [comment]
Still facing this same issue today on Windows 10 and 11. @matetothde could you explain a bit more how to do this (beginner programmer here). Where do you find the subfolder and how do you add this to PATH?

**Comment by mherrmann** [comment]
This is fixed now in version 1.2.4 of [fbs Pro](https://build-system.fman.io/pro).
