### ISSUE TITLE
Trying to freeze the tutorial app but stuck at fbs freeze

### ISSUE THREAD

**Issue by rmndrs89** [mherrmann/fbs-tutorial#42]
Dear all,

I am trying to take the tutorial, however I am stuck at `fbs freeze`, where I get the following error code:

`fbs freeze
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\fbstut\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\envs\fbstut\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\fbstut\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\PyInstaller\building\utils.py", line 662, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\fbstut\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\anaconda3\envs\fbstut\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\fbstut\Scripts\fbs.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\programdata\anaconda3\envs\fbstut\lib\site-packages\fbs\freeze\__init__.py", line 47, in run_pyinstaller
    run(args, check=True)
  File "c:\programdata\anaconda3\envs\fbstut\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'TutorialApp', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--windowed', '--icon', 'C:\\WINDOWS\\system32\\src\\main\\icons\\Icon.ico', '--distpath', 'C:\\WINDOWS\\system32\\target', '--specpath', 'C:\\WINDOWS\\system32\\target\\PyInstaller', '--workpath', 'C:\\WINDOWS\\system32\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\programdata\\anaconda3\\envs\\fbstut\\lib\\site-packages\\fbs\\freeze\\hooks', '--runtime-hook', 'C:\\WINDOWS\\system32\\target\\PyInstaller\\fbs_pyinstaller_hook.py', 'C:\\WINDOWS\\system32\\src\\main\\python\\main.py']' returned non-zero exit status 1.`

Perhaps it's noteworthy, but I am working on Win 10, and have installed PyQt5==5.12.2 rather than PyQt5==5.9.2

Best,
Robbin

**Comment by mherrmann** [comment]
From https://build-system.fman.io/troubleshooting:

> The most common mistake
> fbs only supports Python versions 3.5 and 3.6! Many problems reported by users are caused by using a non-standard distribution such as Anaconda, or Python 3.7
