### ISSUE TITLE
raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['pyinstaller',

### ISSUE THREAD

**Issue by gauthierbuttez** [mherrmann/fbs-tutorial#48]
Hi,

First of all congratulation for this project. It looks great.

I just found your tool and follow your tutorial. I get an issue with your tutorial code.

My environment is:
conda 4.8.4
python 3.8
PyQt5 5.12.3
Pyinstaller 3.4
Mac OS X Catalina 10.15.6

```

(base) gbbtz@MacBookgb myapp_0002 % fbs freeze
Traceback (most recent call last):
  File "/Users/gbbtz/opt/anaconda3/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 654, in strip_paths_in_code
    consts = tuple(
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 655, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 662, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
Traceback (most recent call last):
  File "/Users/gbbtz/opt/anaconda3/bin/fbs", line 8, in <module>
    sys.exit(_main())
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/fbs/builtin_commands/__init__.py", line 114, in freeze
    freeze_mac(debug=debug)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/fbs/freeze/mac.py", line 22, in freeze_mac
    run_pyinstaller(args, debug)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/fbs/freeze/__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "/Users/gbbtz/opt/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'Mymyapp', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--windowed', '--icon', '/Users/gbbtz/CFF Dropbox/gb Buttez/cff/Python/myapp_0002/target/Icon.icns', '--osx-bundle-identifier', 'com.gb.mymyapp', '--distpath', '/Users/gbbtz/CFF Dropbox/gb Buttez/cff/Python/myapp_0002/target', '--specpath', '/Users/gbbtz/CFF Dropbox/gb Buttez/cff/Python/myapp_0002/target/PyInstaller', '--workpath', '/Users/gbbtz/CFF Dropbox/gb Buttez/cff/Python/myapp_0002/target/PyInstaller', '--additional-hooks-dir', '/Users/gbbtz/opt/anaconda3/lib/python3.8/site-packages/fbs/freeze/hooks', '--runtime-hook', '/Users/gbbtz/CFF Dropbox/gb Buttez/cff/Python/myapp_0002/target/PyInstaller/fbs_pyinstaller_hook.py', '/Users/gbbtz/CFF Dropbox/gb Buttez/cff/Python/myapp_0002/src/main/python/main.py']' returned non-zero exit status 1.


```

Do you know this issue?

**Comment by mherrmann** [comment]
Yes. Read the tutorial again.
