### ISSUE TITLE
FBS Freeze fail on Windows with Python3.8

### ISSUE THREAD

**Issue by shakeelansari63** [mherrmann/fbs-tutorial#52]
FBS Freeze on Windows with Python 3.8 fails. Here is the stack trace.
```
Traceback (most recent call last):
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\utils.py", line 654, in strip_paths_in_code
    consts = tuple(
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\utils.py", line 655, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\utils.py", line 662, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python38\Scripts\fbs-script.py", line 11, in <module>
    load_entry_point('fbs==0.9.0', 'console_scripts', 'fbs')()
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\fbs\__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\fbs\cmdline.py", line 32, in main
    fn(*args)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\fbs\builtin_commands\__init__.py", line 120, in freeze
    freeze_windows(debug=debug)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\fbs\freeze\windows.py", line 18, in freeze_windows
    run_pyinstaller(args, debug)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\site-packages\fbs\freeze\__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "c:\users\xxxx\appdata\local\programs\python\python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'My Project', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--windowed', '--icon', 'E:\\project-case\\src\\main\\icons\\Icon.ico', '--distpath', 'E:\\project-case\\target', '--specpath', 'E:\\project-case\\target\\PyInstaller', '--workpath', 'E:\\project-case\\target\\PyInstaller', '--additional-hooks-dir', 'c:\\users\\xxxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\fbs\\freeze\\hooks', '--runtime-hook', 'E:\\project-case\\target\\PyInstaller\\fbs_pyinstaller_hook.py', 'E:\\project-case\\src\\main\\python\\main.py']' returned non-zero exit status 1.
```

**Comment by mherrmann** [comment]
fbs only supports Python 3.5 and 3.6 for now.
