### ISSUE TITLE
fbs freeze failed

### ISSUE THREAD

**Issue by UmangRajpara13** [mherrmann/fbs-tutorial#55]
"Ubuntu 20.04, python 3.6 in venv" 

Traceback (most recent call last):
  File "/home/umang/Desktop/repos/Venv/bin/fbs", line 8, in <module>
    sys.exit(_main())
  File "/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/__main__.py", line 17, in _main
    fbs.cmdline.main()
  File "/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/cmdline.py", line 32, in main
    fn(*args)
  File "/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/builtin_commands/__init__.py", line 125, in freeze
    freeze_ubuntu(debug=debug)
  File "/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/freeze/ubuntu.py", line 4, in freeze_ubuntu
    freeze_linux(debug)
  File "/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/freeze/linux.py", line 8, in freeze_linux
    run_pyinstaller(debug=debug)
  File "/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/freeze/__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'Awesome', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--distpath', '/home/umang/Desktop/repos/Venv/target', '--specpath', '/home/umang/Desktop/repos/Venv/target/PyInstaller', '--workpath', '/home/umang/Desktop/repos/Venv/target/PyInstaller', '--additional-hooks-dir', '/home/umang/Desktop/repos/Venv/lib/python3.6/site-packages/fbs/freeze/hooks', '--runtime-hook', '/home/umang/Desktop/repos/Venv/target/PyInstaller/fbs_pyinstaller_hook.py', '/home/umang/Desktop/repos/Venv/src/main/python/main.py']' returned non-zero exit status 1.

**Comment by amarnathreddy0201** [comment]
```[3012] Failed to execute script ```

is this error ,so please help me too

**Comment by UmangRajpara13** [comment]
i dropped python for desktop application development.
i moved to javascript and use electron framework.

**Comment by Ing-Josef-Klotzner** [comment]
try to add **just** this line in your python program:
from fbs_runtime.application_context.PyQt5 import ApplicationContext

do NOT use this:

```
    appctxt = ApplicationContext()
    ....
    exit_code = appctxt.app.exec_()
    sys.exit(exit_code)

```

# leave your main like it was -- like this:

```
def main():
    app = QtWidgets.QApplication(argv)
    t = Tetris()
    t.show()
    exit(app.exec_())

```

**Comment by Ing-Josef-Klotzner** [comment]
> `[3012] Failed to execute script `
> 
> is this error ,so please help me too

try to add **just** this line in your python program:
from fbs_runtime.application_context.PyQt5 import ApplicationContext

do NOT use this:

```
    appctxt = ApplicationContext()
    ....
    exit_code = appctxt.app.exec_()
    sys.exit(exit_code)

```
leave your main like it was -- like this:

```
def main():
    app = QtWidgets.QApplication(argv)
    t = Tetris()
    t.show()
    exit(app.exec_())

```
